
development:
  adapter: postgresql
  encoding: unicode
  database: Cloud_Community_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: Cloud_Community_test
  pool: 5
 

production:
  adapter: postgresql
  encoding: unicode
  database: Cloud_Community_production
  pool: 5

